use_frameworks!

platform :ios, '9.0'

target 'HESCIOSFramework_Example' do
   pod 'HESCIOSFramework', :path => '../'
#  pod 'HESCIOSFramework'

  target 'HESCIOSFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
